### ISSUE TITLE
Correct Cable Combination

### ISSUE THREAD

**Issue by CaseyJNova** [fred-dev/KinectV2_Syphon#1]
Great project, looking forward to interfacing with the Kinect V2 on the Mac soon. Mad respect.

Can you clarify if this uses the "Kinect Adapter for Windows" to interface with a Mac (provides USB I'm assuming)?

Cheers,

P.S. Sorry, not really a issue. But there isn't a forum for projects either.

**Comment by fred-dev** [comment]
Yes the version that is designed for the video games console does not have
a USB 3 plug, you can get an adaptor for these kinects to plug into any
computer.

Everything is here
https://www.microsoft.com/en-us/kinectforwindows/purchase/default.aspx#tab=2
You need the sensor and the Kinect Adapter for Windows.

Fred

On Thu, Aug 27, 2015 at 7:02 AM, Casey J Scalf notifications@github.com
wrote:

> Great project, looking forward to interfacing with the Kinect V2 on the
> Mac soon. Mad respect.
> 
> Can you clarify if this uses the "Kinect Adapter for Windows" to interface
> with a Mac (provides USB I'm assuming)?
> 
> Cheers,
> 
> P.S. Sorry, not really a issue. But there isn't a forum for projects
> either.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fred-dev/KinectV2_Syphon/issues/1.

## 

Frederick Rodrigues
+31685253512
pipslab.nl
http://www.fredrodrigues.net/

**Comment by CaseyJNova** [comment]
Hi Fred,

I purchased the hardware and cables.

Sensor: http://www.amazon.com/gp/product/B00NMST9G8?psc=1&redirect=true&ref_=oh_aui_detailpage_o04_s00
Adapter: http://www.amazon.com/gp/product/B00NMSHT7E?psc=1&redirect=true&ref_=oh_aui_search_detailpage

However, I only get a blank feed from the app. I see it listed in the USB Prober but nothing is coming through the feeds.

![screen shot 2015-09-22 at 12 51 47 pm](https://cloud.githubusercontent.com/assets/7865492/10029848/33f2a6d0-6129-11e5-8ea8-3934b3cbaa9c.png)

I tried changing the OpenCL device number but that did not change anything. Are there any drivers I need to install? Is this plug and play? Are there other pieces I am missing?

Thanks for he help I really look forward to finally getting the Kinect V2 up and running on the Mac!

**Comment by CaseyJNova** [comment]
Hi, I am wondering why this is still not working?

Did I get the wrong sensor? Are there any drivers that need to be installed? The screen is just blank and so is the Syphon feed.

Thanks for any tips. I am looking forward to getting this working.

**Comment by fred-dev** [comment]
This is an issue with libfreenect2 there has been a known fix for a long time.

Ensure power is applied to Kinect v2 via power supply
Plug in USB 3 connection to computer
Attempt to run this app... likely it won't work. Quit the app.
Unplug power to Kinect v2 but do not unplug the USB 3 cable
Restore power to Kinect.
Run the app. Voila! It works.

This app has been updated and should have less trouble with that from now on.
