### ISSUE TITLE
calibrated view

### ISSUE THREAD

**Issue by micrem73** [fred-dev/KinectV2_Syphon#3]
Not exactly an issue, but a feature request - sorry, there's no other place to post it.

Would be beautiful to have a calibrated output between Colour and Depth. So that one could extract easily a shilouette of the person standing in front on the sensor.

Anyway, I confirm the actual build works with Yosemite.

**Comment by fred-dev** [comment]
So far the calibration I get access to is not so good, also as there is no openNi or Nite available for OSX with kinect 2 there is no silhouette available, just the camera streams. You may get something like this with the depth camera but it is far from the person cutouts that you may have used before.
